name: Deploy frontend

on:
  push:
    paths:
      - "holding-page/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd holding-page && yarn install && cd ../
      - name: Build
        run: cd holding-page && CI=false yarn run build && cd ../
      - name: Deploy the holding page
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./holding-page/build
